Repository Klipper3d/klipper, pull requests merged in 2024-03, with the labels that each got.

#6523 stm32: Fix USART3 ALT pinout on STM32G0
  src/stm32/stm32f0_serial.c
Labels: pending feedback

#6418 Replace max_accel_to_decel with minimum_cruise_ratio
  config/printer-anycubic-4maxpro-2.0-2021.cfg
  config/printer-sovol-sv05-2022.cfg
  docs/Config_Changes.md
  docs/Config_Reference.md
  docs/G-Codes.md
  docs/Kinematics.md
  docs/Resonance_Compensation.md
  docs/Status_Reference.md
  klippy/extras/resonance_tester.py
  klippy/toolhead.py
Labels: reviewer needed

#6488 Adding support for 100pin version of H32F460 and Tenlog D3 32bit printer
  src/hc32f460/gpio.c
  src/hc32f460/hard_pwm.c
Labels: pending feedback

#6502 tmc2240: add ADC voltage formatters
  klippy/extras/tmc2240.py
Labels: reviewer needed

#6515 Update Measuring_Resonances.md
  docs/Measuring_Resonances.md
Labels: pending feedback, reviewer needed
