Repository Klipper3d/klipper, pull requests merged in 2024-04, with the labels that each got.

#6505 install-ubuntu-22.04: Mark as executable
  scripts/install-ubuntu-22.04.sh
Labels: reviewer needed

#6545 stm32: fix support for USARTs on STM32G0B0
  src/stm32/stm32f0_serial.c
Labels: pending feedback

#6504 remove dead code
  klippy/configfile.py
  klippy/extras/dotstar.py
  klippy/extras/endstop_phase.py
  klippy/extras/idle_timeout.py
  klippy/extras/input_shaper.py
  klippy/kinematics/hybrid_corexy.py
  klippy/kinematics/hybrid_corexz.py
  klippy/mcu.py
  klippy/toolhead.py
Labels: pending feedback, reviewer needed

#6540 Define a default for virtual_sdcard on_gcode_error
  docs/Config_Changes.md
  docs/Config_Reference.md
  klippy/extras/virtual_sdcard.py
Labels: reviewer needed

#6560 sensors: add sht31 support
  docs/Config_Reference.md
  docs/Status_Reference.md
  klippy/extras/sht3x.py
  klippy/extras/temperature_sensors.cfg
Labels: pending feedback

#6549 Add kconfig options for rp2040 uart
  src/rp2040/Kconfig
  src/rp2040/serial.c
Labels: pending feedback

#6509 Update Measuring_Resonances.md
  docs/Measuring_Resonances.md
Labels: pending feedback, reviewer needed
