Repository Klipper3d/klipper, pull requests merged in 2025-04, with the labels that each got.

#6876 stm32: Add support for additional i2c bus
  src/stm32/i2c.c
Labels: enhancement

#6863 stm32: Turn on can.c error interrupts
  src/stm32/can.c
Labels: reviewer needed

#6769 Temperature combined: handle temp monitors and I2C sensors
  klippy/extras/temperature_combined.py
Labels: bug, reviewer needed

#6881 axis_twist_compensation: Fix AttributeError on klippy connect state
  klippy/extras/axis_twist_compensation.py
Labels: bug

#6882 tmc: add missing freewheel config options 2208/2209/2130
  docs/Config_Reference.md
  klippy/extras/tmc2130.py
  klippy/extras/tmc2208.py
  klippy/extras/tmc2209.py
Labels: enhancement

#6902 stm32: Add support for spi6 on stm32f42x chips
  src/stm32/spi.c
Labels: enhancement

#6906 spi_flash: fix spi bus switch
  scripts/spi_flash/spi_flash.py
Labels: bug
